[theme]
# Primary accent color for interactive elements.
primaryColor = "#71C971"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F5F5F7"

# Color used for almost all text.
textColor = "#1D1D1F"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "serif"
